version: "3.7"

services:
    elasticsearch:
        image: elasticsearch:7.9.1
        container_name: elasticsearch
        restart: always
        ports:
            - 5535:9200
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl --silent --fail localhost:9200/_cluster/health || exit 1",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        environment:
            discovery.type: single-node
            bootstrap.memory_lock: true
            http.cors.enabled: true
            http.cors.allow-origin: "*"
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        volumes:
            - type: volume
              source: logs
              target: /var/log/elasticsearch
            - type: volume
              source: esdata
              target: /var/lib/elasticsearch
    kibana:
        image: kibana:7.9.1
        container_name: kibana
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_URL: http://elasticsearch:9200
        ports:
            - 5533:5601
        links:
            - elasticsearch
        depends_on:
            - elasticsearch
        volumes:
            - type: volume
              source: logs
              target: /var/log/kibana
    oap:
        image: apache/skywalking-oap-server:8.1.0-es7
        container_name: oap
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        restart: always
        ports:
            - 11800:11800
            - 12800:12800
        healthcheck:
            test: ["CMD-SHELL", "/skywalking/bin/swctl"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        environment:
            SW_STORAGE: elasticsearch7
            SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
    ui:
        image: apache/skywalking-ui:8.1.0
        container_name: ui
        depends_on:
            - oap
        links:
            - oap
        restart: always
        ports:
            - 18080:8080
        environment:
            SW_OAP_ADDRESS: oap:12800
volumes:
    esdata:
        driver: local
    logs:
        driver: local
