version: "3.7"

services:
    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        command: redis-server /etc/redis/redis.conf
        volumes:
            - /opt/redis_data:/data
            - ./coturn/redis.conf:/etc/redis/redis.conf:ro
        ports:
            - 6379:6379

    coturn:
        image: instrumentisto/coturn
        restart: always
        depends_on:
            - redis
        volumes:
            - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
            - /opt/certs/cert.pem:/etc/ssl/certs/cert.pem
            - /opt/certs/privkey.pem:/etc/ssl/private/privkey.pem
        network_mode: host
        deploy:
            resources:
                limits:
                    memory: 1024M

    kms:
        image: kurento/kurento-media-server
        restart: always
        depends_on:
            - coturn
        environment:
            - KMS_STUN_IP=${REAL_EXTERNAL_IP}
            - KMS_STUN_PORT=${stun_port:-3478}
            - KMS_TURN_URL=aidhgj:aidhgj9527@${REAL_EXTERNAL_IP}:${stun_port:-3478}?transport=udp
        ports:
            - 8888:8888
