version: "3.7"
services:
    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        volumes:
            - /opt/redis_data:/data

    coturn:
        image: instrumentisto/coturn
        restart: always
        depends_on:
            - redis
        volumes:
            - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
            - /opt/certs/cert.pem:/etc/ssl/certs/cert.pem
            - /opt/certs/privkey.pem:/etc/ssl/private/privkey.pem
        network_mode: host

    kms:
        image: kurento/kurento-media-server
        restart: always
        depends_on:
            - coturn
        environment:
            - KMS_STUN_IP=172.18.5.10
            - KMS_STUN_PORT=3478
            - KMS_TURN_URL=aidhgj:aidhgj9527@172.18.5.10:3478?transport=udp
        ports:
            - 8888:8888
