version: "3.7"
services:
    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        volumes:
            - /opt/redis_data:/data
        networks:
            kms_net:
                ipv4_address: 172.18.5.9
    coturn:
        image: instrumentisto/coturn
        restart: always
        ports:
            - 3478:3478
            - 3478:3478/udp
        command:
            - --log-file=stdout
        depends_on:
            - redis
        volumes:
            - ./cotrun/turnserver.conf:/etc/coturn/turnserver.conf:ro
            - /opt/certs/cert.pem:/etc/ssl/certs/cert.pem
            - /opt/certs/privkey.pem:/etc/ssl/certs/privkey.pem
        networks:
            kms_net:
                ipv4_address: 172.18.5.10
    kms:
        image: kurento/kurento-media-server
        restart: always
        depends_on:
            - coturn
        environment:
            - KMS_STUN_IP=172.18.5.10
            - KMS_STUN_PORT=3478
            - KMS_TURN_URL=aidhgj:aidhgj9527@172.18.5.10:3478?transport=udp
        ports:
            - 8888:8888
        networks:
            kms_net:
                ipv4_address: 172.18.5.11
networks:
    kms_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16
