version: "3.7"
services:
    kms:
        image: kurento/kurento-media-server
        restart: always
        environment:
            - KMS_STUN_IP=172.18.5.11
            - KMS_STUN_PORT=3478
            - KMS_TURN_URL=aidhgj:aidhgj9527@172.18.5.11:3478?transport=udp
        ports:
            - 8888:8888
        networks:
            kms_net:
                ipv4_address: 172.18.5.10
    coturn:
        image: instrumentisto/coturn
        restart: always
        ports:
            - 3478:3478
            - 49152-65535:49152-65535/udp
        volumes:
            - ${PWD}/cotrun/turnserver.conf:/etc/coturn/turnserver.conf
            #- ${PWD}/coturn/privkey.pem:/etc/ssl/private/privkey.pem
            #- ${PWD}/coturn/cert.pem:/etc/ssl/certs/cert.pem
            - /home/jacksoncy/work/nginx/cert.pem:/etc/ssl/certs/cert.pem
            - /home/jacksoncy/work/nginx/privkey.pem:/etc/ssl/certs/privkey.pem
        networks:
            kms_net:
                ipv4_address: 172.18.5.11
networks:
    kms_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16
