version: "3.7"

services:
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "8044:6379"
        volumes:
            - /opt/redis_data:/data
