version: "3.7"
services:
    mariadb-master:
        image: mariadb
        container_name: mariadb-master
        restart: always
        environment:
            - MYSQL_USER=2uchat
            - MYSQL_PASSWORD=1#aHh2
            - MYSQL_ROOT_PASSWORD=F4i^f9
        ports:
            - 8033:3306
        volumes:
            - ./mysql_conf/master/my.cnf:/etc/mysql/my.cnf
            - /data0/mariadb:/var/lib/mysql
        networks:
            - database-net
    mariadb-slave:
        image: mariadb
        container_name: mariadb-slave
        restart: always
        depends_on:
            - mariadb-master
        environment:
            - MYSQL_MASTER_HOST=mariadb-master
            - MYSQL_MASTER_PORT_NUMBER=3306
            - MYSQL_ROOT_PASSWORD=F4i^f9
            - MYSQL_USER=2uchat
            - MYSQL_PASSWORD=1#aHh2
            - MASTER_MYSQL_ROOT_PASSWORD=F4i^f9
        ports:
            - 8034:3306
        volumes:
            - ./mysql_conf/slave/my.cnf:/etc/mysql/my.cnf
            - /data1/mariadb:/var/lib/mysql
        networks:
            - database-net
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "8044:6379"
        volumes:
            - /opt/redis_data:/data
        networks:
            - database-net
    elasticsearch:
        image: elasticsearch:7.9.3
        container_name: elasticsearch
        restart: always
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - http.cors.enabled=true
            - http.cors.allow-origin=*
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - /data0/elasticsearch/data:/usr/share/elasticsearch/data
            - /data0/elasticsearch/logs:/usr/share/elasticsearch/logs
        ports:
            - 8055:9200
        networks:
            - database-net
networks:
    database-net:
        driver: bridge
