version: "3.7"
services:
    mongodb-primary:
        image: mongo
        container_name: mongodb-primary
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12^xH0
        command: mongod --dbpath /data/db --keyFile /mongo/mongo.key --replSet BigBoss
        ports:
            - 8077:27017
        volumes:
            - /data0/mongo:/data/db
            - ./keyfiles/primary:/mongo
        networks:
            mongo-net:
                ipv4_address: 172.18.5.10
    mongodb-secondary0:
        image: mongo
        container_name: mongodb-secondary0
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12^xH0
        command: mongod --dbpath /data/db --keyFile /mongo/mongo.key --replSet BigBoss
        ports:
            - 8078:27017
        volumes:
            - /data1/mongo:/data/db
            - ./keyfiles/secondary0:/mongo
        networks:
            mongo-net:
                ipv4_address: 172.18.5.11
    mongodb-secondary1:
        image: mongo
        container_name: mongodb-secondary1
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12^xH0
        command: mongod --dbpath /data/db --keyFile /mongo/mongo.key --replSet BigBoss
        ports:
            - 8079:27017
        volumes:
            - /data2/mongo:/data/db
            - ./keyfiles/secondary1:/mongo
        networks:
            mongo-net:
                ipv4_address: 172.18.5.12
    mongo-set-setup:
        image: mongo
        container_name: mongo-set-setup
        depends_on:
            - mongodb-primary
            - mongodb-secondary0
            - mongodb-secondary1
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongodb-primary
            - MONGO2=mongodb-secondary0
            - MONGO3=mongodb-secondary1
            - RS=BigBoss
            - PASSWORD=12^xH0
        entrypoint: ["/scripts/setup.sh"]
        networks:
            mongo-net:
                ipv4_address: 172.18.5.13
    mongo-configsvr0:
        image: mongo
        container_name: configsvr0
        restart: always
        command: mongod --replSet BigSur --configsvr --dbpath /data/configdb --logpath /data/configdb/log/configsvr.log
        ports:
            - 8074:27017
        volumes:
            - /data0/configdb:/data/configdb
        networks:
            mongo-net:
                ipv4_address: 172.18.5.14
    mongo-configsvr1:
        image: mongo
        container_name: configsvr1
        restart: always
        command: mongod --replSet BigSur --configsvr --dbpath /data/configdb --logpath /data/configdb/log/configsvr.log
        ports:
            - 8075:27017
        volumes:
            - /data1/configdb:/data/configdb
        networks:
            mongo-net:
                ipv4_address: 172.18.5.15
    mongo-configsvr2:
        image: mongo
        container_name: configsvr2
        restart: always
        command: mongod --replSet BigSur --configsvr --dbpath /data/configdb --logpath /data/configdb/log/configsvr.log
        ports:
            - 8076:27017
        volumes:
            - /data2/configdb:/data/configdb
        networks:
            mongo-net:
                ipv4_address: 172.18.5.16
    mongos:
        image: mongo
        container_name: mongos
        command: mongos --configdb BigSur/172.18.5.14:27017,172.18.5.15:27017,172.18.5.16:27017
        restart: always
        depends_on:
            - mongo-configsvr0
            - mongo-configsvr1
            - mongo-configsvr2
        ports:
            - 8072:27017
        networks:
            mongo-net:
                ipv4_address: 172.18.5.17
    mongo-init:
        image: mongo
        depends_on:
            - mongo-configsvr0
            - mongo-configsvr1
            - mongo-configsvr2
        restart: on-failure:5
        command:
            - mongo
            - --host mongo-configsvr0:27017
            - --eval
            - 'rs.initiate({ _id: "BigSur", configsvr: true, members: [{_id:0,host:"mongo-configsvr0:27017"},{_id:1,host:"mongo-configsvr1:27017"},{_id:2,host:"mongo-configsvr2:27017"}]})'
    mongos-init:
        image: mongo
        depends_on:
            - mongos
        restart: on-failure:5
        command:
            - mongo
            - --host mongo-configsvr0:27017
            - --eval
            - 'sh.addShard("BigBoss/mongodb-primary:27017,mongodb-secondary0:27017,mongodb-secondary1:27017")'
networks:
    mongo-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16
