version: "3.7"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12^xH0
        command: mongod --dbpath /data/db --port 27017 --auth --replSet BigBoss --shardsvr
        ports:
            - 8077:27017
        volumes:
            - /data0/mongo:/data/db
        networks:
            - mongo_net

    mongo-setup:
        image: mongo
        container_name: mongo-setup
        depends_on:
            - mongodb
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO11=mongodb
            - RS=BigBoss
            - PASSWORD=12^xH0
        entrypoint: ["/scripts/init-shard.sh"]
        restart: on-failure:3
        networks:
            - mongo_net

networks:
    mongo_net:
        driver: bridge
