version: "3.7"
services:
    mongo-configsvr0:
        image: mongo
        container_name: mongo-configsvr0
        restart: always
        command: mongod --configsvr --replSet BigSur --dbpath /data/configdb --port 27019
        ports:
            - 8074:27019
        volumes:
            - /data0/configdb:/data/configdb
            - ./keyfiles/configsvr0:/mongo
        networks:
            mongo_net:
                ipv4_address: 172.18.5.14
    mongo-configsvr1:
        image: mongo
        container_name: mongo-configsvr1
        restart: always
        command: mongod --configsvr --replSet BigSur --dbpath /data/configdb --port 27019
        ports:
            - 8075:27019
        volumes:
            - /data1/configdb:/data/configdb
        networks:
            mongo_net:
                ipv4_address: 172.18.5.15
    mongo-configsvr2:
        image: mongo
        container_name: mongo-configsvr2
        restart: always
        command: mongod --configsvr --replSet BigSur --dbpath /data/configdb --port 27019
        ports:
            - 8076:27019
        volumes:
            - /data2/configdb:/data/configdb
        networks:
            mongo_net:
                ipv4_address: 172.18.5.16
    mongo-init:
        image: mongo
        container_name: mongo-init
        depends_on:
            - mongo-configsvr0
            - mongo-configsvr1
            - mongo-configsvr2
        restart: on-failure:5
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongo-configsvr0
            - MONGO2=mongo-configsvr1
            - MONGO3=mongo-configsvr2
            - RS=BigSur
        entrypoint: ["/scripts/config.sh"]
        networks:
            mongo_net:
                ipv4_address: 172.18.5.18
    mongodb-primary:
        image: mongo
        container_name: mongodb-primary
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12^xH0
        command: mongod --dbpath /data/db --keyFile /mongo/mongo.key --shardsvr --replSet BigBoss
        ports:
            - 8077:27017
        volumes:
            - /data0/mongo:/data/db
            - ./keyfiles/primary:/mongo
        networks:
            mongo_net:
                ipv4_address: 172.18.5.10
    mongodb-secondary0:
        image: mongo
        container_name: mongodb-secondary0
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12^xH0
        command: mongod --dbpath /data/db --keyFile /mongo/mongo.key --shardsvr --replSet BigBoss
        ports:
            - 8078:27017
        volumes:
            - /data1/mongo:/data/db
            - ./keyfiles/secondary0:/mongo
        networks:
            mongo_net:
                ipv4_address: 172.18.5.11
    mongodb-secondary1:
        image: mongo
        container_name: mongodb-secondary1
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12^xH0
        command: mongod --dbpath /data/db --keyFile /mongo/mongo.key --shardsvr --replSet BigBoss
        ports:
            - 8079:27017
        volumes:
            - /data2/mongo:/data/db
            - ./keyfiles/secondary1:/mongo
        networks:
            mongo_net:
                ipv4_address: 172.18.5.12
    mongo-set-setup:
        image: mongo
        container_name: mongo-set-setup
        depends_on:
            - mongodb-primary
            - mongodb-secondary0
            - mongodb-secondary1
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongodb-primary
            - MONGO2=mongodb-secondary0
            - MONGO3=mongodb-secondary1
            - RS=BigBoss
            - PASSWORD=12^xH0
        entrypoint: ["/scripts/setup.sh"]
        networks:
            mongo_net:
                ipv4_address: 172.18.5.13
    mongos:
        image: mongo
        container_name: mongos
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12^xH0
        command: mongos --configdb BigSur/172.18.5.14:27019,172.18.5.15:27019,172.18.5.16:27019 --keyFile /mongo/mongo.key --port 27018
        depends_on:
            - mongo-configsvr0
            - mongo-configsvr1
            - mongo-configsvr2
        volumes:
            - ./keyfiles/mongos:/mongo
        ports:
            - 8072:27018
        networks:
            mongo_net:
                ipv4_address: 172.18.5.17

    mongos-init:
        image: mongo
        container_name: mongos-init
        depends_on:
            - mongos
        restart: on-failure:5
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongos
            - PASSWORD=12^xH0
        entrypoint: ["/scripts/mongos.sh"]
        networks:
            mongo_net:
                ipv4_address: 172.18.5.19
networks:
    mongo_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16
