version: "3.7"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12^xH0
        command: mongod --dbpath /data/db --port 27017 --auth --replSet BigBoss --shardsvr
        ports:
            - 8077:27017
        volumes:
            - /data0/mongo:/data/db
            - ./scripts:/scripts
        networks:
            - mongo_net
networks:
    mongo_net:
        driver: bridge
