version: "3.7"
services:
    nexus3:
        image: sonatype/nexus3
        container_name: nexus3
        restart: always
        ports:
            - 8081:8081
        volumes:
            - /data/nexus-data:/nexus-data
