version: "3.7"

services:
    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=F4i^f9
        ports:
            - 8033:3306
        volumes:
            - ./my.cnf:/etc/mysql/my.cnf
            - /opt/mariadb:/var/lib/mysql
        networks:
            - database_net

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - database_net

networks:
    database_net:
        driver: bridge
