version: "3.7"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: elasticsearch
        restart: always
        ports:
            - 8055:9200
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - http.cors.enabled=true
            - http.cors.allow-origin=*
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        volumes:
            - /opt/elasticsearch/logs:/usr/share/elasticsearch/logs
            - /opt/elasticsearch/data:/usr/share/elasticsearch/data
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        networks:
            - elastic

    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.0
        container_name: kibana
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_URL: http://elasticsearch:9200
        ports:
            - 5601:5601
        links:
            - elasticsearch
        depends_on:
            - elasticsearch
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        networks:
            - elastic

    oap:
        image: apache/skywalking-oap-server:latest-es7
        container_name: oap
        environment:
            SW_STORAGE: elasticsearch7
            SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        restart: always
        ports:
            - 11800:11800
            - 12800:12800
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        healthcheck:
            test: ["CMD-SHELL", "/skywalking/bin/swctl"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        networks:
            - elastic

    ui:
        image: apache/skywalking-ui
        container_name: ui
        restart: always
        environment:
            SW_OAP_ADDRESS: oap:12800
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        depends_on:
            - oap
        links:
            - oap
        ports:
            - 18080:8080
        networks:
            - elastic

networks:
    elastic:
        driver: bridge
