version: "3.7"

services:
    oap:
        image: apache/skywalking-oap-server:latest-es7
        container_name: oap
        restart: always
        environment:
            SW_STORAGE: elasticsearch
            SW_STORAGE_ES_CLUSTER_NODES: ${ES_URL}
        ports:
            - 11800:11800
            - 12800:12800
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        healthcheck:
            test: ["CMD-SHELL", "/skywalking/bin/swctl"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        networks:
            - skywalking

    ui:
        image: apache/skywalking-ui
        container_name: ui
        restart: always
        environment:
            SW_OAP_ADDRESS: oap:12800
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        depends_on:
            - oap
        links:
            - oap
        ports:
            - 18080:8080
        networks:
            - skywalking

networks:
    skywalking:
        driver: bridge
