version: "3"
services:
    mariadb-master:
        image: mariadb
        container_name: mariadb-master
        restart: always
        environment:
            - MARIADB_REPLICATION_MODE=master
            - MYSQL_USER=2uchat
            - MYSQL_PASSWORD=1#aHh2
            - MYSQL_ROOT_PASSWORD=F4i^f9
        ports:
            - 8033:3306
        volumes:
            - ./mysql_conf/master/my.cnf:/etc/mysql/my.cnf
            - /data0/mariadb:/var/lib/mysql
    mariadb-slave:
        image: mariadb
        container_name: mariadb-slave
        restart: always
        depends_on:
            - mariadb-master
        environment:
            - MYSQL_REPLICATION_MODE=slave
            - MYSQL_MASTER_HOST=mariadb-master
            - MYSQL_MASTER_PORT_NUMBER=3306
            - MYSQL_ROOT_PASSWORD=F4i^f9
            - MYSQL_USER=2uchat
            - MYSQL_PASSWORD=1#aHh2
            - MASTER_MYSQL_ROOT_PASSWORD=F4i^f9
        ports:
            - 8034:3306
        volumes:
            - ./mysql_conf/slave/my.cnf:/etc/mysql/my.cnf
            - /data1/mariadb:/var/lib/mysql
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "8044:6379"
        volumes:
            - ./redis_data:/data
