version: "3"
services:
    mariadb-master:
        image: mariadb
        container_name: mariadb-master
        restart: always
        environment:
            - MYSQL_USER=2uchat
            - MYSQL_PASSWORD=1#aHh2
            - MYSQL_ROOT_PASSWORD=F4i^f9
        ports:
            - 8033:3306
        volumes:
            - /data0/mariadb:/var/lib/mysql
        command:
            [
                "--log-bin=mysql-master-bin",
                "--server-id=1",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--innodb_flush_log_at_trx_commit=1",
                "--sync_binlog=1",
            ]
    mariadb-slave:
        image: mariadb
        container_name: mariadb-slave
        restart: always
        depends_on:
            - mariadb-master
        environment:
            - MYSQL_ROOT_PASSWORD=F4i^f9
            - MASTER_MYSQL_ROOT_PASSWORD=F4i^f9
        ports:
            - 8034:3306
        volumes:
            - /data1/mariadb:/var/lib/mysql
        command:
            [
                "--server-id=2",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--relay-log=mysql-slave-relay-bin",
            ]
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "8044:6379"
        volumes:
            - ./redis_data:/data
