version: "3.7"

services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        volumes:
            - /opt/zk_data:/data
        ports:
            - 8082:2181
        networks:
            - kafka_net

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        restart: always
        depends_on:
            - zookeeper
        ports:
            - 8088:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
            KAFKA_CREATE_TOPICS: test:1:1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        networks:
            - kafka_net

    kafka_manager:
        image: hlebalbau/kafka-manager:stable
        container_name: kafka_manager
        restart: always
        depends_on:
            - zookeeper
            - kafka
        ports:
            - 8090:9000
        environment:
            ZK_HOSTS: zookeeper:2181
            APPLICATION_SECRET: letmein
        networks:
            - kafka_net

networks:
    kafka_net:
        driver: bridge
