version: "3.7"

services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        volumes:
            - /opt/zk_data:/data
        ports:
            - 2181:2181
        networks:
            kafka_net:
                ipv4_address: 172.18.5.10

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        restart: always
        ports:
            - 8088:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 172.18.5.11
            KAFKA_CREATE_TOPICS: "test:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        networks:
            kafka_net:
                ipv4_address: 172.18.5.11

networks:
    kafka_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16
