version: "3.7"

services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        volumes:
            - /opt/zk_data:/data
        ports:
            - 2181:2181
        network_mode: "host"

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        restart: always
        depends_on:
            - zookeeper
        ports:
            - 8088:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_CREATE_TOPICS: "test:1:1"
            KAFKA_ZOOKEEPER_CONNECT: 127.0.0.1:2181
        network_mode: "host"

    kafka_manager:
        image: hlebalbau/kafka-manager:stable
        container_name: kafka_manager
        restart: always
        depends_on:
            - zookeeper
            - kafka
        ports:
            - 8090:9000
        environment:
            ZK_HOSTS: 127.0.0.1:2181
            APPLICATION_SECRET: "random-secret"
        network_mode: "host"
