version: "3.7"

services:
    kafka_manager:
        image: hlebalbau/kafka-manager:stable
        container_name: kafka_manager
        restart: always
        ports:
            - 8080:9000
        environment:
            APPLICATION_SECRET: random-secret
