version: "3.7"

services:
    redis:
        image: redis
        container_name: redis
        restart: always
        command: redis-server /etc/redis.conf
        ports:
            - 8044:6379
        volumes:
            - ./redis.conf:/etc/redis.conf:ro
            - /opt/redis_data:/data
